name: Testing & deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Running install process
        run: yarn install

      - name: Download test file
        uses: wei/wget@v1.1.1
        with:
          args: -O sample.html https://httpbin.org/html

      - name: Download backup archives
        uses: wei/wget@v1.1.1
        with:
          args: -O archiveDocsBackup.tar.gz ${{ secrets.ARCHIVE_BACKUP }}

      - name: Download backup images
        uses: wei/wget@v1.1.1
        with:
          args: -O archiveImagesBackup.tar.gz ${{ secrets.IMAGES_BACKUP }}

      - name: Read
        run: ls -lha

      - name: Unzip backup files
        run: |
          tar -zxvf archiveDocsBackup.tar.gz
          tar -zxvf archiveImagesBackup.tar.gz

      - name: Running building
        run: yarn build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
